tezosConfig:
  server:
    URL: "http://localhost:20000/"

  wallet:
    #Alice private key, don't use it in your wallet
    privateKey: "edsk2ssz9Yx48dVpPCMMDc2aNGDumoqmToirUXGaBnoydtRbaj1BCm"

  contracts:
    quorumAddress: "KT1J7wioz6tqPbk4b6vyeHR8mntdrT3QJ3yx"
    depositAddress: "KT1Hy9LYKs1Ja4EN6HBdhpFQkJWvAQWpUJEB"

ipfsConfig:
  server: "localhost:5001"

everscaleConfig:
  servers:
    - "http://localhost:3412"
    - "http://0.0.0.0:3412"
    - "http://127.0.0.1:3412"

  contracts:
    depositContract:
      abi: "./test.abi.json"
      address: "0:0744a77fba05e67b848068566f3d7c78de9eb68acd6fd894937ae85bad500a81"
