tezosConfig:
  server:
    URL: "http://localhost:20000/"

  wallet:
    #Alice private key, don't use it in your wallet
    privateKey: "edsk2ssz9Yx48dVpPCMMDc2aNGDumoqmToirUXGaBnoydtRbaj1BCm"

  contracts:
    quorumAddress: "KT1Q4WueKgWtBz2yFvFZN8hT63C3FYqxtqiZ"
    depositAddress: "KT1V3AG34mWtuUE5DDrnyX1JSEayKuMpt71V"

ipfsConfig:
  server: "localhost:5001"

everscaleConfig:
  servers:
    - "http://localhost:3412"
    - "http://0.0.0.0:3412"
    - "http://127.0.0.1:3412"
  signerPrivateKey: "6fef706751776d43c0277f76458e2ab32146b324991daf46f40c919a81f136fe"
  signerPublicKey: "5bd8c119fcf53cf32878b0b961198858928464663465bcbfb1033bdd71d665a2"
  contracts:
    depositContract:
      abi: "./DemoTokenImpl.abi.json"
      address: "0:a30fa0ae97a921beaef229f7352952e5de65f44bb340ebc4499bfd0e97064caa"
